[2022-09-05 15:13:23,502][DEBUG|main.py:87] >> login init_process close...
